# Build pipeline for monogame projects
# Env: Dotnet 8 (monogame image ver. 1.3)
# Last modified: 2024-10
# Author: Ralf Hesse
#
# Required secrets:
#   game_project: Project Name (.sln solution name)
#   sonar_token: Sonar authentication token
#   project_key: Sonar project key (e.g. Sopra24:Gruppe-1)

# customized clone step (executed before ci pipeline is started)
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 50
      lfs: false

# the build pipeline
# commits in main and release trigger a full analyzed build
# every other commit gets compiled only
steps:  
  # STEP 1: run compiler in debug mode (every branch except release)
  compile:
    image: thowl/monogame:1.3
    commands:
      - dotnet restore $${GAME_PROJECT}.sln
      - dotnet build --configuration Debug $${GAME_PROJECT}.sln
    secrets: [ game_project ]
    when:
        - branch:
            exclude: [main, release]
          event: push

  # STEP 1 (main/release): build the app and run a full scan on sonarqube (only in release)
  # HACK: builds in the experimental branch publish their results to sonarqube too
  compile-and-analyze:
    image: thowl/monogame:1.3
    environment:
      - SONAR_HOST=https://sonar.aes.th-owl.de
    commands:
      - dotnet restore $${GAME_PROJECT}.sln
      - dotnet sonarscanner begin /k:$PROJECT_KEY /d:sonar.scanner.skipJreProvisioning=true /d:sonar.host.url=$SONAR_HOST /d:sonar.token=$SONAR_TOKEN /v:$CI_COMMIT_BRANCH
      - dotnet build --configuration Release $${GAME_PROJECT}.sln
      - dotnet sonarscanner end /d:sonar.token=$SONAR_TOKEN
    secrets: [ project_key, sonar_token, game_project ]
    when:
      - branch: [main, release]
        event: [push, tag, manual]

  # STEP 2 (main/release): package the app (currently only a windows binary is published)
  deploy:
    image: thowl/monogame:1.3
    commands:
        - dotnet publish --runtime win-x64 --configuration Release --self-contained=false $${GAME_PROJECT}
        - mkdir dist
        - 7z a dist/$${GAME_PROJECT}_win.zip $${GAME_PROJECT}/bin/Release/net6.0/win-x64/publish/*
        - echo "ready for deployment:"
        - ls dist/*
    secrets: [ game_project ]
    when:
      - branch: release 
        event: tag
      

  # STEP 3 (tag only): append the binaries to gitea's release 
  publish:
    image: woodpeckerci/plugin-gitea-release
    settings:
        base_url: https://gitea.aes.th-owl.de
        api_key:
          from_secret: gitea_token
        files:
          - dist/*
        target: release
    secrets: [ game_project, gitea_token ]
    when:
      - event: tag
